import { Outfit } from "next/font/google";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ['latin']
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* suppressHydrationWarning will stop React complaining about extra attrs */}
        <body suppressHydrationWarning className={outfit.className}>
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
